Still not finished.

diff --git a/bin/populate b/bin/populate
--- a/bin/populate
+++ b/bin/populate
@@ -29,15 +29,27 @@ function populate_caches() {
     sensitive-certificate-authority.git
   )
 
+  branch="$(git branch | grep '^\*' | sed 's/^* //')" \
+    || fail "Failed to find branch."
+
   for repo in "${repos_untracked[@]}"; do
-    git clone --bare "https://git@github.com/abugher/${repo}" "${repo}" \
-      || fail "Failed to clone repo:  '${repo}'"
+    clone_repo "https://git@github.com/abugher/${repo}"
   done
-  # Name of fileserver is hardcoded here.  Perhaps not ideal.
   for repo in "${repos_untracked_sensitive[@]}"; do
-    git clone --bare "ansible@files:/storage/control-center/${repo}" "${repo}" \
-      || fail "Failed to clone repo:  '${repo}'"
+    # Name of fileserver is hardcoded here.  Perhaps not ideal.
+    clone_repo "ansible@files:/storage/control-center/${repo}"
   done
+}
+
+
+function clone_repo() {
+  address="${1}"
+  git clone --bare "${address}" "${repo}" \
+    || fail "Failed to clone repo:  '${repo}'"
+  ( cd "${repo}"; git symbolic-ref HEAD refs/heads/"${branch}"; ) \
+    || fail "Failed to set branch for repo:  branch='${branch}'; repo='${repo}'"
+  git push -u origin "${branch}" \
+    || fail "Failed to set upstream for repo:  '${repo}'"
 }
 
 
